spring:
  application:
    name: MatchApplication
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:liquibase/db.changelog-master.xml

logging:
  level:
    org.springframework: INFO
server:
  port: 8180
